stages:
  - build
  - deploy
  - clean

variables:
  GIT_SUBMODULE_STRATEGY: recursive

docker_build:
  stage: build
  before_script:
    - source ~/.functions
    - set_docker_pic_et
  script: 
    - docker build --build-arg HUGO_BASE_URL=http://polenord.et.ci.alterway.fr --build-arg HUGO_PORT=80 -t hugo-polenord .

docker_deploy:
  stage: deploy
  environment:
    name: ET
    url: http://polenord.et.ci.alterway.fr/
  before_script:
    - source ~/.functions
    - set_docker_pic_et
  script:
    - docker run --rm -d -p 1313 --name polenord-${CI_COMMIT_SHA} hugo-polenord
  when: manual

docker_remove:
  stage: clean
  before_script:
    - source ~/.functions
    - set_docker_pic_et
  script:
    - docker rm -f polenord-${CI_COMMIT_SHA}
  when: manual

